plugins { id 'com.android.application' }

android {
    namespace 'pl.alfalauncher.seven'
    compileSdk 35

    defaultConfig {
        applicationId 'pl.alfalauncher.seven'
        minSdk 24
        targetSdk 28
        versionCode 14
        versionName '1.4'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
